### ISSUE TITLE
Allow notes to be stored in nested folders/notebooks

### ISSUE THREAD

**Issue by OJ7** [omarmir/nanote#22]
I would like to import my existing notes into Nanote, but all of my files are stored in nested directories. It would be great (for portability) to be able to access/edit files that are stored anywhere within the `notes` directory, not just at the root of it.

My use case is to combine this with [Obsidian](https://obsidian.md/) to have my notes accessible via a web browser, in a lightweight fashion (I have a lot of plugins that make Obsidian slow to load for quick notes).

**Comment by omarmir** [comment]
I can look at this. It presents a few challenges that I would be keen to get your thoughts on:

- How does it work UI wise? Especially with unlimited nesting?
- Should there be a limit to nesting?
- Maximum URL length is 2048 chars and maximum file path length can be smaller (260 chars to 4095) - currently if you exceed that the md file fails to create. Does this make sense?
- The higher level of nesting you have the slower the homepage will load (it has to traverse the directory structure to get the files and their dates/times etc). This will cost the speed that you are after though likely not by a meaningful amount.
- Right now the directory structure is simple: `[root] -> [notebook] -> node.md & [note -> attachments.ext]`. So this means either you cannot notebook inside an existing notebook where the nested notebook and an existing note can share a name OR we need to put the attachments in a different root. so It looks like:
`[root] -> [notebook] -> note.md & [notebook -> ... nesting]` and `[root2] -> [notebook] -> [note] -> attachments.ext &  [notebook -> ... nesting]`

I am not averse to adding this in, I've already run into issues myself where I think I would prefer to have some nesting but I haven't quite figured out what I want to implement.

**Comment by omarmir** [comment]
Let me think about it for a couple of days as I finish the file uploading feature. Then I will add this to the next on the list since it will impact the other features I have planned for myself (archiving, trash, and encryption)

**Comment by omarmir** [comment]
@OJ7 realistically how deeply nested are your notes? I went through mine and it's 2 max (folder > folder > notes).

I can get past most of the issues but the UI seems really messy as it gets deeply nested.

**Comment by omarmir** [comment]
Ok, so I've made decisions on how to implement it. The nesting will be unlimited.
Attachments/uploads will go in their own base folder as to not interfere with the subdirs in notes.
URLs will change from the current scheme

the backend is almost done, you can see it in the nested branch. I expect this should be out in a couple of days at most. Some testing would be great @OJ7 - would you be able to do some quick test runs if I publish a beta tagged docker image?

**Comment by omarmir** [comment]
About 50% done, was a significant change (as per usual I underestimated the effort).

**Comment by omarmir** [comment]
@OJ7 and @Fybre Ok I think I have a working sample. Do not use this on production data (use a clone of your data or something!). Also do not use the file upload feature yet - its not stable. Please test thoroughly and try to make it break. Let me know what doesn't work or work as expected.

Here is the compose file (note the nested tag and change the variables/paths as needed):

```
version: '3.8'
services:
  nanote:
    image: omarmir/nanote:nested
    ports:
      - '3030:3000'
    environment:
      - NOTES_PATH=/notes
      - SECRET_KEY=<yourkey>
    volumes:
      - /path/to/local/folder:/notes
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/api/health']
      interval: 30s # Check every 30 seconds
      timeout: 10s # Fail if no response in 10s
      retries: 3 # Mark as unhealthy after 3 failed checks
      start_period: 30s # Wait 10s before starting checks
```
